version: "3.9"
services:
  web-server:
    container_name: web-server
    build:
      ./dockernote_web
    ports:
      - 8080:8080
    develop:
      watch:
        - action: rebuild
          path: ./dockernote_web
    depends_on:
      - file_server
      - balancer
      - db-web

  balancer:
    container_name: balancer
    build:
      ./balancer
    expose:
      - 8000
    develop:
      watch:
        - action: rebuild
          path: ./balancer
    depends_on:
      - db-files
      - nb_worker_1
      - nb_worker_2
      - nb_worker_3

  file_server:
    container_name: file_server
    build:
      ./file_server
    ports:
      - 8000:8000
    expose:
      - 8000
    develop:
      watch:
        - action: rebuild
          path: ./file_server
    depends_on:
      - db-files

  nb_worker_1:
    container_name: nb_worker_1
    build:
      ./dockernote_worker
    expose:
      - 8000
    develop:
      watch:
        - action: rebuild
          path: ./dockernote_worker
    depends_on:
      - file_server

  nb_worker_2:
    container_name: nb_worker_2
    build:
      ./dockernote_worker
    expose:
      - 8000
    develop:
      watch:
        - action: rebuild
          path: ./dockernote_worker
    depends_on:
      - file_server

  nb_worker_3:
    container_name: nb_worker_3
    build:
      ./dockernote_worker
    expose:
      - 8000
    develop:
      watch:
        - action: rebuild
          path: ./dockernote_worker
    depends_on:
      - file_server

  db-web:
    container_name: db-web
    image: postgres
    user: postgres
    restart: "on-failure"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
    ports: # TODO : hide this port after testing is done
      - 5432:5432
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  db-files:
    container_name: db-files
    image: mongo
    restart: "on-failure"
    volumes:
      - db-data:/data/db
    expose:
      - 27017
    ports: # TODO : hide this port after testing is done
      - 27017:27017
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.stats()" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
